apiVersion: v1
kind: Service
metadata:
  name: echo-backend-{{ .Values.color }}
  labels:
    app: echo-backend-{{ .Values.color }}
spec:
  type: ClusterIP # can this be "headless"?
# ClusterIP: None # can this be "headless"?
  ports:
  - port: 80
  selector:
    app: echo-backend-{{ .Values.color }}
