apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: demos
spec:
  egressFilter:
    type: DROP_ALL   # network access ONLY via routes to VirtualService resources defined in this mesh (preferred)
  # type: ALLOW_ALL  # unrestricted network access (switch on for temporary internet access)
  namespaceSelector:
    matchLabels:
      mesh: demos    # associate this mesh with appropriately labeled namespaces
