apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: vs-echo-backend
spec:
  awsName: vs-echo-backend.{{ .Release.Namespace }}.svc.cluster.local # required for FQDN support
  provider:
    virtualRouter:
      virtualRouterRef:
        name: vr-echo-backend
