apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: vs-echo-frontend
spec:
  awsName: vs-echo-frontend.{{ .Release.Namespace }}.svc.cluster.local # required for FQDN support
  provider:
    virtualNode:
        virtualNodeRef:
            name: vn-echo-frontend
