apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-frontend-{{ .Values.color }}
  labels:
    app: echo-frontend-{{ .Values.color }}
spec:
  replicas: {{ default 3 .Values.replicas }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: echo-frontend-{{ .Values.color }}
  template:
    metadata:
      labels:
        app: echo-frontend-{{ .Values.color }}
    spec:
      containers:
      - name: echo-frontend
        image: {{ .Values.registry }}/echo-frontend:{{ .Values.version }}
        imagePullPolicy: Always
        env:
        - name: BACKEND
          value: {{ default "none" .Values.backend }}
        resources:
          requests:
            memory: 200Mi
            cpu: 200m
