apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: echo-frontend-{{ .Values.color }}
spec:
  minReplicas: 30
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: echo-frontend-{{ .Values.color }}
