apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: echo-frontend-{{ .Values.color }}
spec:
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.targetCPUUtilizationPercentage }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: echo-frontend-{{ .Values.color }}